import type { PageContent } from "@/content/types";
import { REFUND_POLICY } from "@/content/packages";

export const packages: PageContent = {
  meta: {
    title: "Singapore PR Consultant Fees & Packages | Fixed Prices — GetSGPR",
    description: "From structured DIY preparation to full application management. Every package shows exactly what is included, what is not and what happens after submission.",
    path: "/packages",
  },
  shapes: "plain",
  blocks: [
    {
      kind: "hero", variant: "plain",
      centered: true,
      eyebrow: "Packages",
      title: "Choose how much support you need. Know the price before you speak to us.",
      sub: "From structured DIY preparation to full application management. Every package shows exactly what is included, what is not and what happens after submission.",
    },
    { kind: "trust" },
    {
      kind: "packages",
      showNotFor: true,
      note: "Prices in SGD, [[include / exclude]] GST. ICA application fees and third-party costs are shown separately. No hidden consultancy fees. No approval guarantees. **Refunds:** " + REFUND_POLICY,
    },
    {
      kind: "honest", tone: "alt", tight: true,
      title: "No hidden consultancy fees. No approval guarantees.",
      text: "Your scope and fee are agreed in writing before work begins. ICA application fees, translations, notarisation and other third-party costs are shown separately where applicable. Prices in SGD, [[include / exclude]] GST at the prevailing rate.",
    },
    {
      kind: "table",
      title: "Compare everything.",
      columns: ["Feature", "SGPR Lite", "SGPR Partnered", "Premium Concierge"],
      rows: [
        ["PR Readiness diagnostic", "Self-assessment", "Full report", "Full report"],
        ["Individual strategy report", "—", "✓", "✓"],
        ["1:1 consultation", "—", "1 × 60 min", "As scoped, typically 2–3"],
        ["Named consultant", "—", "✓", "✓"],
        ["Named case manager", "—", "—", "✓"],
        ["Personalised document gap list", "—", "✓", "✓"],
        ["ICA-linked checklist and organiser", "✓", "✓", "✓"],
        ["Evidence matrix", "—", "—", "✓"],
        ["Document quality control", "Self, with checklist", "Spot check", "Full"],
        ["Forms completed by GetSGPR", "—", "—", "✓"],
        ["Forms reviewed by GetSGPR", "—", "✓", "✓"],
        ["Cover letter and narrative", "Template", "Reviewed", "Written by us"],
        ["Evidence consistency audit", "Self, with checklist", "✓", "✓ plus final audit"],
        ["Revision rounds", "—", "2", "3"],
        ["Translations and notarisation", "—", "Guidance", "Coordinated, at cost"],
        ["ICA submission", "Guide", "Guide", "Step-by-step assistance"],
        ["Post-submission support", "Guide", "Guide", "Advisory to outcome, live updates"],
        ["Post-outcome strategy review", "—", "Limited, 30 min", "✓"],
        ["Rejection strategy session", "—", "—", "✓"],
        ["Appeal or reapplication assessment", "—", "Add-on S$[[x]]", "1 included"],
        ["Appeal drafting", "—", "Add-on S$[[x]]", "[Included / Add-on S$[[x]]]"],
        ["Secure shared Drive workspace", "Download area", "✓", "✓"],
        ["Response time", "—", "Agreed review schedule", "Agreed review schedule"],
        ["Support period", "90 days of updates", "30 days after final review", "Until outcome, plus [[30]] days"],
        ["Languages", "English", "English, Mandarin, Malay, Tamil", "English, Mandarin, Malay, Tamil"],
        ["Additional family members", "—", "S$[[x]] each", "S$[[x]] adult · S$[[x]] child"],
        ["GST", "[[Incl. / Excl.]]", "[[Incl. / Excl.]]", "[[Incl. / Excl.]]"],
      ],
    },
    {
      kind: "cards", tone: "alt", columns: 3,
      title: "Which one is you?",
      cards: [
        {
          badge: "SGPR Lite", tone: "teal",
          title: "The organised self-starter",
          text: "You have a stable job, clean documents and time. You want a structure to follow and the confidence you have not missed something.",
          link: { label: "About SGPR Lite →", href: "/sgpr-lite-diy-tier" },
        },
        {
          badge: "SGPR Partnered", tone: "violet",
          title: "The professional who wants a second pair of eyes",
          text: "You will do the work, but you want someone experienced to find the gaps and inconsistencies before ICA does.",
          link: { label: "About SGPR Partnered →", href: "/sgpr-partnered-do-with-you" },
        },
        {
          badge: "Premium Concierge", tone: "amber",
          title: "The family, the founder or the previously rejected applicant",
          text: "Your case has moving parts, your time is scarce, or the last attempt did not work. You want one person accountable for the whole thing.",
          link: { label: "About Premium Concierge →", href: "/sgpr-premium-concierge" },
        },
      ],
      note: "Not sure? The free [Readiness Review](/pr-readiness-review) recommends a package at the end.",
    },
    {
      kind: "table",
      title: "Applying as a family.",
      sub: "A family application is one application with several people's evidence in it. The extra work is in keeping every person's records consistent with the others, which is why we price per additional member rather than per family.",
      columns: ["Applicant", "SGPR Partnered", "Premium Concierge"],
      rows: [
        ["Main applicant", "S$497", "S$1,997"],
        ["Spouse", "S$[[x]]", "S$[[x]]"],
        ["Each child under 21", "S$[[x]]", "S$[[x]]"],
        ["Parent (where eligible)", "S$[[x]]", "S$[[x]]"],
      ],
      note: "SGPR Lite covers a family application at the single price; the toolkit includes family checklists.",
    },
    {
      kind: "items", tone: "alt", columns: 2,
      title: "Fees that are not ours.",
      items: [
        { title: "ICA fees", text: "ICA charges a processing fee per applicant when you submit, and further fees on approval for the entry permit, re-entry permit and identity card. Current amounts are on ica.gov.sg. [[Insert amounts with the date checked.]]" },
        { title: "Translations", text: "Documents not in English must be translated by an accepted translator. At cost, typically S$[[x]]–[[x]] per page." },
        { title: "Notarisation and certification", text: "Where ICA or the issuing body requires it. At cost." },
        { title: "Courier and printing", text: "At cost, rarely more than S$[[x]]." },
      ],
      foot: { text: "We do not mark up third-party costs, and we tell you before any are incurred." },
    },
    {
      kind: "prose",
      title: "How long it takes, and what a revision round is.",
      content: [
        { p: "Preparation time depends on how quickly you can obtain employer letters, transcripts and other required records. ICA states that PR applications will be processed within six months when all required documents are submitted and in order, although some applications may take longer. ICA's processing period begins after submission, and we cannot shorten it." },
        { p: "A revision round is one complete pass by us over your forms, cover letter and supporting statements, with written comments returned to you. Partnered includes two rounds and Concierge includes three. The clock on your support period starts on the date of your final review." },
      ],
    },
    {
      kind: "prose", tone: "alt", id: "appeal",
      title: "What happens if I am rejected?",
      content: [
        { p: "Every Premium Concierge client receives a post-outcome strategy review, including one appeal or reapplication assessment if needed. We assess whether new information supports an appeal or whether strengthening the profile and reapplying later is more appropriate. Any further drafting or submission support is agreed in writing before work begins." },
        { p: "Partnered clients receive a 30-minute post-outcome review. Any further appeal or reapplication work is scoped separately." },
        { p: "**Appeals are lodged through ICA's prescribed e-Service and assessed by ICA on their own merits. There is no separate channel for consultants, and we will never claim one.**" },
        { p: "Fees already paid are not refunded on rejection: " + REFUND_POLICY },
      ],
    },
    {
      kind: "items", columns: 3,
      title: "What you can expect from us.",
      items: [
        { title: "Response time", text: "We reply to initial enquiries within 24 hours. Review dates and ongoing response times are agreed with you when work begins." },
        { title: "Consultations", text: "By video call or at our Tradehub 21 office, by appointment. Available times are confirmed when you book." },
        { title: "Languages", text: "English, Mandarin, Malay and Tamil." },
        { title: "Cancellations", text: "Free with 24 hours' notice. Later cancellations count as one consultation." },
        { title: "Missing documents", text: "Where a document genuinely cannot be obtained, we draft a declaration letter explaining its absence at no extra charge." },
        { title: "Where your documents go", text: "Lite clients download the toolkit and keep their own files. Partnered and Concierge clients receive a secure shared Drive workspace, with access limited to the people on their case and revoked when the case closes. We never take documents by WhatsApp. [Full details](/privacy-data-security)" },
      ],
    },
    {
      kind: "faq", tone: "alt",
      title: "Package questions.",
      openFirst: true,
      items: [
        { q: "Can I upgrade later?", a: "Yes. Lite and Partnered fees are credited in full against Premium Concierge within [[90]] days of purchase." },
        { q: "Do you offer refunds?", a: "Lite is a digital product and is non-refundable once downloaded. For Partnered and Concierge, [[state the policy, for example: a full refund if you cancel before the strategy consultation, and a pro-rated refund for unused stages thereafter]]." },
        { q: "What if I cannot get a document?", a: "Tell us. Where a record genuinely cannot be obtained, we draft a declaration letter explaining its absence at no extra charge." },
        { q: "Do you guarantee approval?", a: "No. ICA makes every decision on the merits of the application. Anyone who promises approval is either misleading you or breaking Singapore's consumer protection rules." },
        { q: "How do I pay?", a: "[[Card, PayNow or bank transfer.]] Lite is paid online at purchase. Partnered and Concierge are invoiced after the scope is agreed, before work begins." },
      ],
    },
    {
      kind: "cta",
      title: "Ready to choose?",
      sub: "Not sure which fits? Start the free Readiness Review and we will recommend one.",
      buttons: [
        { label: "Get SGPR Lite", href: "/sgpr-lite-diy-tier", style: "light" },
        { label: "Book SGPR Partnered", href: "/contact", style: "outline-dark" },
        { label: "Book a Concierge call", href: "/contact", style: "outline-dark" },
      ],
    },
  ],
};
